#!/usr/bin/env python3
# Copyright 2026, The DisplayXR Project and its contributors
# SPDX-License-Identifier: Apache-2.0
"""
Build the OpenPBR swatch pack: one USD scene per OpenPBR reference material,
each the ASWF StandardShaderBall wearing that material.

Inputs (pinned in scenes/openpbr-swatches/scene.json):
  * the OpenPBR repo's examples/open_pbr_*.mtlx (Apache-2.0) and MaterialX's
    own OpenPBR examples, when given;
  * usd-wg/assets full_assets/StandardShaderBall (CC-BY-4.0).

Output layout (everything relative, so the pack can sit anywhere):

    <out>/StandardShaderBall/...       the ball's layers, geometry, maps (as published)
    <out>/materials/<name>.mtlx        the example documents (unchanged)
    <out>/swatches/<name>.usda         one wrapper per material
    <out>/MODIFICATIONS.md             what this script did (CC-BY 4.0 requires it)

A wrapper sublayers only the ball's `shaderball.usda` and `camera.usda`. It
leaves out the stock scene root, which pulls `example_materials.usda`, and
`environment.usda`, a closed studio box: viewed from outside it hides the
ball, and its maps go through inline networks a glTF-class viewer does not
bake. The wrapper then:

  * references the triangulated surface. The subdiv variant needs a subdivision
    step most real-time loaders lack;
  * binds the swatch material (`references = @x.mtlx@</MaterialX/Materials/N>`)
    to the ball's outer surface;
  * rewires the stock `neutral` material (base and core) to a constant
    mid-grey OpenPBR shader. Upstream routes its surface outputs through
    NodeGraph outputs, and its emission image has a file only inside a variant.
    tinyusdz's converter rejects both, and that fails the whole scene.

None of the source files is edited. Every change lives in the wrapper
layer, as a USD opinion.

Usage:
    build_swatches.py <out-dir> --ball <StandardShaderBall dir> --mtlx <dir> [--mtlx <dir> ...]
"""
import argparse
import re
import shutil
import sys
from pathlib import Path

WRAPPER = """#usda 1.0
(
    doc = "OpenPBR swatch: {title}. Generated by displayxr-reference-scenes scripts/build_swatches.py"
    defaultPrim = "standard_shader_ball_scene"
    metersPerUnit = 0.01
    upAxis = "Y"
    subLayers = [
        @../StandardShaderBall/layers/shaderball.usda@,
        @../StandardShaderBall/layers/camera.usda@
    ]
)

def Xform "standard_shader_ball_scene"
{{
    def Xform "shader_ball" (
        prepend apiSchemas = ["MaterialBindingAPI"]
        prepend references = @../StandardShaderBall/material_surface_geo/triangulated.usda@
    )
    {{
        rel material:binding = </standard_shader_ball_scene/materials/swatch>
    }}

    over "materials"
    {{
        over "neutral"
        {{
            token outputs:surface.connect = </standard_shader_ball_scene/materials/neutral/usdpreview/usdpreviewsurface1.outputs:surface>
            token outputs:mtlx:surface.connect = </standard_shader_ball_scene/materials/neutral/dxr_neutral.outputs:out>

            def Shader "dxr_neutral"
            {{
                uniform token info:id = "ND_open_pbr_surface_surfaceshader"
                color3f inputs:base_color = (0.18, 0.18, 0.18)
                float inputs:specular_roughness = 0.5
                token outputs:out
            }}
        }}

        def Material "swatch" (
            prepend references = @../materials/{mtlx}@</MaterialX/Materials/{material}>
        )
        {{
        }}
    }}
}}
"""


def materials_in(mtlx):
    """surfacematerial names in a MaterialX document, in file order."""
    return re.findall(r'<surfacematerial\s+name="([^"]+)"', mtlx.read_text(errors="replace"))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("out")
    ap.add_argument("--ball", required=True, help="usd-wg/assets full_assets/StandardShaderBall")
    ap.add_argument("--mtlx", action="append", required=True, help="folder of OpenPBR .mtlx examples")
    a = ap.parse_args()
    out, ball = Path(a.out).resolve(), Path(a.ball).resolve()
    if out.exists():
        shutil.rmtree(out)
    (out / "materials").mkdir(parents=True)
    (out / "swatches").mkdir()

    # The ball as published, minus what the wrappers never reach.
    keep = ["layers/shaderball.usda", "layers/camera.usda", "material_surface_geo/triangulated.usda",
            "LICENCE", "README.md"]
    keep += [p.relative_to(ball).as_posix() for p in (ball / "maps").glob("*")]
    for rel in keep:
        (out / "StandardShaderBall" / rel).parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(ball / rel, out / "StandardShaderBall" / rel)

    index, skipped = [], []
    for folder in a.mtlx:
        for f in sorted(Path(folder).glob("*.mtlx")):
            if not re.search(r"<open_pbr_surface\b", f.read_text(errors="replace")):
                skipped.append(f"{f.name} (no open_pbr_surface)")
                continue
            if (out / "materials" / f.name).exists():
                skipped.append(f"{f.name} (duplicate name)")
                continue
            shutil.copy2(f, out / "materials" / f.name)
            for mat in materials_in(f):
                stem = f.stem.removeprefix("open_pbr_")
                name = stem if len(materials_in(f)) == 1 else f"{stem}__{mat}"
                (out / "swatches" / f"{name}.usda").write_text(
                    WRAPPER.format(title=mat.replace("_", " "), mtlx=f.name, material=mat))
                index.append((name, f.name, mat))

    (out / "swatches" / "INDEX.tsv").write_text(
        "swatch\tmtlx\tmaterial\n" + "".join(f"{n}\t{m}\t{t}\n" for n, m, t in index))
    (out / "MODIFICATIONS.md").write_text(f"""# Modifications from the originals

Assembled by `scripts/build_swatches.py` (displayxr-reference-scenes).

- **StandardShaderBall** (usd-wg/assets, CC-BY-4.0): only the files the
  wrappers reach are included (`layers/shaderball.usda`, `layers/camera.usda`,
  `material_surface_geo/triangulated.usda`, `maps/`). None of them is modified.
  Each wrapper in `swatches/` overrides the scene with USD opinions: it binds a
  swatch material to the ball's outer surface, and rewires the `neutral`
  material's surface outputs to a constant mid-grey OpenPBR shader that the
  wrapper defines.
- **OpenPBR example materials** (Apache-2.0): copied unchanged into
  `materials/`.
{''.join(f'- Not included: {s}{chr(10)}' for s in skipped)}
{len(index)} swatches.
""")
    print(f"{len(index)} swatches -> {out}; {len(skipped)} skipped")
    for s in skipped:
        print("  skipped", s)


if __name__ == "__main__":
    sys.exit(main())
